source 'https://github.com/CocoaPods/Specs.git'
source 'http://gerrit.3g.net.cn/gomo_ios_specs'

platform :ios, '8.0'

target 'Co_pay_PayNotificationSDK_Example' do
  pod 'Co_pay_PayNotificationSDK', :path => '../'

  target 'Co_pay_PayNotificationSDK_Tests' do
    inherit! :search_paths

    
  end
end
